### ISSUE TITLE
Support custom animations

### ISSUE THREAD

**Issue by ste93cry** [markgoodyear/scrollup#45]
Hello,
I'm using your plugin and it's fantastic. However, I miss an important feature for me: the ability to use custom animations for showing/hiding the button. I see in the README that the `animation` option has three possible values: `none`, `fade` and `slide`. It would be really cool if user could set any animation he wants, or maybe have an option that adds a class when the button is showed so that I can use the CSS3 transitions directly from the style.

**Comment by markgoodyear** [comment]
This is something I've planned for v3. Unfortunately, I can't give a release date on this as I don't always have time to work on it :).

**Comment by ste93cry** [comment]
Glad to know that this is something planned. Can I suggest to add this feature in a minor 2.4 release instead of waiting for v3? I really really need this, but if it's not possible I will find another way to do it until you'll release the new version

**Comment by diomed** [comment]
hi! 
I've found this codepen, and I'm pretty sure all codepens are public free, so I hope you'll customise this in colors and use it for scrollup. .svg would be nice addition:
[.svg to top](http://codepen.io/anon/pen/RPGaXw)

**Comment by markgoodyear** [comment]
@ste93cry Finally got round to pushing up a v3 branch. You can have custom animations on the trigger, and it works nicely with animate.css. No live demo yet, but there's one you can view locally in the repo.
